/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author User
 */
public class kalkuatorbmi extends javax.swing.JFrame {

    /**
     * Creates new form pria
     */
    public kalkuatorbmi() {
        initComponents();
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txthasil3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttinggi = new javax.swing.JTextField();
        txtberat = new javax.swing.JTextField();
        txthasil = new javax.swing.JTextField();
        btnhasil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpesan2 = new javax.swing.JTextField();
        txtpesan3 = new javax.swing.JTextField();
        txtpesan1 = new javax.swing.JTextField();
        txtpesan4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        txthasil3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthasil3.setBorder(null);
        txthasil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasil3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("BMI");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("BERAT BADAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("TINGGI BADAN");

        txthasil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txthasil.setForeground(new java.awt.Color(255, 51, 102));
        txthasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthasil.setBorder(null);
        txthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasilActionPerformed(evt);
            }
        });

        btnhasil.setBackground(new java.awt.Color(204, 204, 204));
        btnhasil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhasil.setForeground(new java.awt.Color(255, 153, 51));
        btnhasil.setText("HITUNG");
        btnhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhasilActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("APLIKASI KALKULATOR ");

        txtpesan2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpesan2.setBorder(null);
        txtpesan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesan2ActionPerformed(evt);
            }
        });

        txtpesan3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpesan3.setBorder(null);
        txtpesan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesan3ActionPerformed(evt);
            }
        });

        txtpesan1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpesan1.setBorder(null);
        txtpesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesan1ActionPerformed(evt);
            }
        });

        txtpesan4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpesan4.setBorder(null);
        txtpesan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesan4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("KG");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("CM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txthasil)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpesan2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpesan3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtpesan4)
                .addContainerGap())
            .addComponent(txtpesan1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnhasil)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(188, 188, 188))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtberat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(btnhasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesan2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesan3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesan4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasilActionPerformed

    private void btnhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhasilActionPerformed
        // TODO add your handling code here:
        float ibm;
        float berat=Float.parseFloat(txtberat.getText());
        float tinggi=Float.parseFloat(txttinggi.getText());
        ibm= berat / (tinggi*2 / 100);
        if(ibm <= 17.0){
            txthasil.setText("BMI ANDA ADALAH"+" "+ibm);
            txtpesan1.setText("BERAT BADAN ANDA TERLALU RENDAH");
            txtpesan2.setText("ATUR POLA MAKAN  ANDA DAN MAKANLAH MAKANAN YANG BERGIZI");
        }
        else if( ibm >= 17.0 && ibm <= 18.4 ){
            txthasil.setText("BMI ANDA ADALAH"+" "+ibm);
            txtpesan1.setText("BERAT BADAN ANDA RENDAH");
            txtpesan2.setText("TINGKATKAN NAFSU MAKAN ANDA ");
            txtpesan3.setText("DAN MAKANLAH MAKANAN YANG BERGIZI ");
        }
        else if( ibm >= 18.5 && ibm <= 25 ){
            txthasil.setText("BMI ANDA ADALAH"+" "+ibm);
            txtpesan1.setText("BERAT BADAN ANDA IDEAL");
            txtpesan2.setText("TERUS TINGKATKAN GAYA HIDUP SEHAT");
        }
        else if( ibm >= 25.1 && ibm < 27){
            txthasil.setText("BMI ANDA ADALAH"+" "+ibm);
            txtpesan1.setText("SEKARANG BERAT BADAN ANDA MULAI GEMUK");
            txtpesan2.setText("TINGKATKAN GAYA HIDUP SEHAT ");
            txtpesan3.setText("CONTROL POLA MAKAN ANDA ");
            txtpesan4.setText ("DAN COBALAH OLAHRAGA DENGAN TERATUR ");
        }
        else{
            txthasil.setText("BMI ANDA ADALAH"+" "+ibm);
            txtpesan1.setText("SEKARANG BERAT BADAN ANDA TERGOLONG OBESITAS");
            txtpesan2.setText("TINGKATKAN GAYA HIDUP SEHAT!!!");
            txtpesan3.setText("CONTROL POLA MAKAN ANDA SEKARANG");
            txtpesan4.setText("DAN MULAI DARI SEKARANG OLAH RAGA DENGAN TERATUR");
    }
        
    }//GEN-LAST:event_btnhasilActionPerformed

    private void txtpesan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesan2ActionPerformed

    private void txtpesan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesan3ActionPerformed

    private void txthasil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasil3ActionPerformed

    private void txtpesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesan1ActionPerformed

    private void txtpesan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesan4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkuatorbmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkuatorbmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkuatorbmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkuatorbmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkuatorbmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txthasil3;
    private javax.swing.JTextField txtpesan1;
    private javax.swing.JTextField txtpesan2;
    private javax.swing.JTextField txtpesan3;
    private javax.swing.JTextField txtpesan4;
    private javax.swing.JTextField txttinggi;
    // End of variables declaration//GEN-END:variables
}
